name: deploy

on:
  create:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build and check
        run: poetry build && poetry check

      - name: Setup environment variables
        run: |
          poetry config pypi-token.pypi ${{ secrets.pypi_password }}

      - name: Publish package to PyPI
        run: poetry publish --username wdsrocha
